config/routes.rb
WebgarbagecollectorR3::Application.routes.draw do

  resources :clips

  resources :videos , :wikis
   

	root :to => 'videos#index'
  match 'videos/:id/get_view_count' => 'videos#get_view_count', :as => :get_view_count
  match 'videos/:id/update_view_count' => 'videos#update_view_count', :as => :update_view_count
  match 'videos/:id/show_wiki' => 'videos#show_wiki', :as => :show_wiki  
  match 'wikis/:id/wiki_ok' => 'wikis#wiki_ok', :as => :wiki_ok
  match 'wikis/:id/wiki_ko' => 'wikis#wiki_ko', :as => :wiki_ko
  match 'videos/uploadprogress/:md5' => 'videos#uploadprogress', :as => :uploadprogress
	

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :wikis
  has_one :clip
  # Paperclip Validations
  validates  :param_title, :param_desc, :presence => true
  validates_attachment_presence :movieclip
  validates_attachment_content_type :movieclip, 
    :content_type => [
      'application/x-shockwave-flash',
      'application/x-shockwave-flash',
      'application/flv',
      'video/x-flv',
      'video/mp4',
      'video/MP4V-ES',
      'video/MPV',
      'video/mpeg4',
      'video/mpeg4-generic',]
  

  # models/product.rb
  def self.search(search)
    if search
      find(:all, :conditions => ['param_title LIKE ? or param_desc LIKE ?', "%#{search}%","%#{search}%"])
    else
      find(:all)
    end
  end

  

  has_attached_file :movieclip,
   :url  => "/:attachment/:md5/:style/:basename.:extension",
   :storage => :filesystem
    
#    :storage        => :s3,
#    :s3_credentials => {
#    :access_key_id     =>'AKIAJDCAFXWTGN5SQINQ',
#    :secret_access_key => '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'
#  },
#    :bucket         => 'webgarbagecollector'

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.xml
  def index
    #    @videos = Video.all
    @videos = Video.search(params[:search])
    #    puts "**********DEBUG*********"
    #    puts system("i=0;while [  $i -lt 10 ];do echo $(s3cmd ls \"s3://webgarbagecollector/home/synaptic/NetBeansProjects/webgarbagecollector/public/movieclips/zelmarou22/original/\") | cut -d \" \" -f3    ;done;");
    #    puts "**********END*********"

    #    respond_to do |format|
    #      format.html # index.html.erb
    #      format.xml  { render :xml => @videos }
    #    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  def show
    @video = Video.find(params[:id])
    @wiki = Wiki.new(:video_id => @video.id)
    respond_to do |format|
      format.html   #show.html.erb
      format.xml  { render :xml => @video }
    end
  end

  def show_wiki
    @video = Video.find(params[:id])
    @wiki = Wiki.new(:video_id => @video.id)
    respond_to do |format|
      format.html { render :layout => "show_wiki" }
      format.js
    end
  end

  # GET /videos/new
  # GET /videos/new.xml
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.xml
  def create
    @video = Video.new(params[:video])
    @site_url = "http://ec2-50-17-168-53.compute-1.amazonaws.com:3000"
    puts "**********DEBUG*********"
    puts request.headers["CONTENT_LENGTH"].to_s()
    puts @video.param_title
    puts "**********END*********"
    @predicted_url = "s3://webgarbagecollector/home/synaptic/NetBeansProjects/webgarbagecollector/public/movieclips/"+@video.md5+"/original/"
    #    system("for ((  i = 0 ;  i <= 100;  i++  )); do   echo $(s3cmd ls c"+@predicted_url+"\")  | cut -d \" \" -f6;sleep 2; done;");
    #    puts("for ((  i = 0 ;  i <= 100;  i++  )); do   echo $(s3cmd ls v"+@predicted_url+"\")  | cut -d \" \" -f6;sleep 2; done;");
    respond_to do |format|
      if @video.save
        puts "URL:"
        puts @video.movieclip.url
        puts "PATH:"
        puts @video.movieclip.path
        #        puts "Video ID is --> "+@video.id.to_s();
        #      @video.param_thumb = @video.movieclip.url[0,@video.movieclip.url.index(".")]+"_thumb.jpg";
        #        @video.param_thumb = @site_url+ "/movieclips/"+@video.param_title.split(' ').join('_')+"_thumb.jpg";
        @local_video_thumb_name = @video.movieclip_file_name.gsub(' ','%20')+"_thumb.jpg" ;
#        @local_video_thumb = "/home/ubuntu/rails/webgarbagecollector/public/movieclips/"+@local_video_thumb_name;
#        @local_video_thumb = "/home/synaptic/NetBeansProjects/webgarbagecollector/public/movieclips/"+@local_video_thumb_name;
#       @local_video_path = @video.movieclip.url[0,@video.movieclip.url.index("?")];
#       @local_video_path = @local_video_path[@local_video_path.index("/webgarbagecollector"),@video.movieclip.url.length ];
#       @local_video_path = @local_video_path[0, @local_video_path.index("/original/")];
#       @video.update_attributes(params[:video]);
        #system("ffmpeg -i public/"+@video.movieclip.url[0,@video.movieclip.url.index("?")]+" -s 100x100 -ss 10 -f image2 -vframes 1 public/"+ @video.param_thumb);
        #system("ffmpeg -i "+@video.movieclip.url[0,@video.movieclip.url.index("?")]+" -s 100x100 -ss 10 -f image2 -vframes 1 "+ @local_video_thumb);
        system("ffmpegthumbnailer -i '"+@video.movieclip.path.gsub(' ','%20')+"' -o "+ @video.movieclip.path.gsub(' ','%20')[0,@video.movieclip.path.index(@video.movieclip_file_name.gsub(' ','%20'))]+"../"+@local_video_thumb_name);
        #puts("ffmpegthumbnailer -i '"+@video.movieclip.path.gsub(' ','%20')+"' -o "+ @video.movieclip.path.gsub(' ','%20')[0,@video.movieclip.path.index(@video.movieclip_file_name)]+@local_video_thumb_name);
        #puts "ffmpegthumbnailer -i '"+@video.movieclip.url[0,@video.movieclip.url.index("?")].gsub(' ','%20')+"' -o "+ @local_video_thumb ;
        #copy the jpg thumb into the s3 bucket
        system("s3cmd put --acl-public --recursive "+@video.movieclip.path.gsub(' ','%20')[0,@video.movieclip.path.gsub(' ','%20').index("/original")]+" s3://webgarbagecollector");
        puts("s3cmd put --acl-public --recursive "+@video.movieclip.path.gsub(' ','%20')[0,@video.movieclip.path.gsub(' ','%20').index("/original")]+" s3://webgabagecollector");
        @video.param_thumb = "http://s3.amazonaws.com/webgarbagecollector/"+@video.movieclip.path.gsub(' ','%20')[0,@video.movieclip.path.index(@video.movieclip_file_name.gsub(' ','%20'))][@video.movieclip.path.gsub(' ','%20').index(@video.md5),@video.movieclip.path.gsub(' ','%20').length]+"../"+@local_video_thumb_name ;
        @video.param_video_url = "http://s3.amazonaws.com/webgarbagecollector/"+@video.movieclip.path.gsub(' ','%20')[@video.movieclip.path.gsub(' ','%20').index(@video.md5),@video.movieclip.path.gsub(' ','%20').length];
        @video.update_attributes(params[:video]);
        format.html { redirect_to( '/wikis/new?video_id='+@video.id.to_s() , :notice => 'Your video was successfully uploaded, thanks. You should now fill the wiki' ) }
        format.xml  { render :xml => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])
    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to(videos_url, :notice => 'Video Wiki was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update_view_count
    @video = Video.find(params[:id])
    if !@video.param_hits
      @video.param_hits = 0
    end
    @video.param_hits += 1
    @video.update_attributes(params[:video])

    render :text => @video.param_hits
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def get_view_count
    @video = Video.find(params[:id])
    render :text => @video.param_hits
  end

  
  # PUT /videos/1
  # PUT /videos/1.xml
  def edit_wiki
    @video = Video.find(params[:id])

  end
  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_url) }
      format.xml  { head :ok }
    end
  end

  def find_by_id (id)
    @video = Video.find(params[:id => id])
  end

  def uploadprogress
   
    @url = "public/movieclips/"+params[:md5]+"/original/Sample_K_flv.flv";
    @command  = %x[ls -l #{@url}  | cut -d " " -f5] ;
    render :text => @command;
    #    respond_to do |format|
    #      format.html {render :layout => false}
    #    render :text => "AJAX OK"
    #    end
  end



end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_show.html.erb
<%#*<p>%>
  <%#*<b>Param title:</b>%>
  <%#=h @video.param_title %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param doc:</b>%>
  <%#=h @video.param_doc %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param size:</b>%>
  <%#=h @video.param_size %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param path:</b>%>
  <%#=h @video.param_path %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param hits:</b>%>
  <%#=h @video.param_hits %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param mark:</b>%>
  <%#=h @video.param_mark %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param desc:</b>%>
  <%#=h @video.param_desc %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param type:</b>%>
  <%#=h @video.param_type %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param title:</b>%>
  <%#=h @video.param_title %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param doc:</b>%>
  <%#=h @video.param_doc %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param size:</b>%>
  <%#=h @video.param_size %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param path:</b>%>
  <%#=h @video.param_path %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param hits:</b>%>
  <%#=h @video.param_hits %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param mark:</b>%>
  <%#=h @video.param_mark %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param desc:</b>%>
  <%#=h @video.param_desc %>
<%#*</p>%>

<%#*<p>%>
  <%#*<b>Param type:</b>%>
  <%#=h @video.param_type %>
<%#*</p>%>

<div id="page">
<!-- this A tag is where your Flowplayer will be placed. it can be anywhere -->
		<a
                  href="<%=video.movieclip.url%>"
			 style="display:block;width:520px;height:330px"
			 id="player">
                </a>


<!-- this will install flowplayer inside previous A- tag. -->

		<script type="text/javascript">
			flowplayer("player", "/flash/flowplayer-3.2.7.swf");
		</script>
 <img alt="Gr" src="/movieclips/1/original/rails.png"></img>
</div>

<%= link_to 'Edit', edit_video_path(video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/_show_wiki.html.erb
<div id="wikis">
<h2>
  <%if @video%>
  <%if @video.wikis.count > 1 %>
    This video has <%=@video.wikis.count%> Wiki(s)
  <%else%>
    This video has no wikis. Please help us identifying this movie!
<%end%>
<%end%>
</h2>
<%#*<div id="sortwikis" style="margin: 0 auto; padding: 0 0;">%>
  <%#*<input  id="sortwikibydate" type="button" value="All Sorted by Date"/>%>
  <%#*<input  id="sortwikibyscore" type="button" value="All Sorted by Score"/>%>
  <%#*</div>%>
<div id="wikis_list">
<ul>
<%=
  if @video
    render :partial => @video.wikis.order("param_count_ok desc") , :locals => {:order  => "param_count_ok desc"}
  end
%>
</ul>
</div>


  <div class="wgc-bubble" style="width: 400px; text-align: center;">

<%= if @video
  form_for @wiki , :remote => true do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error")%>
        prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |msg| %>
        <li><%= msg%>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.hidden_field :video_id %>

<h3>Add new wiki</h3>

  <p>Date of creation<br/>
    <%= f.date_select   :param_wiki_date %>
  </p>
  <p>Author<br/>
    <%=f.text_field   :param_wiki_author %>
  </p>
  <p>Counrty from<br/>
    <%=f.text_field   :param_wiki_country %>
  </p>
  <p>Clip history<br/>
    <%=f.text_area   :param_wiki_story %>
  </p>
  <p>Web relative links<br/>
    <%=f.text_field   :param_wiki_links %>
  </p>

  <div class="field">
    <%= f.label :param_desc %><br />
    <%= f.text_field :param_desc %>
  </div>

  <div class="field">
    <%= f.label :param_submitter %><br />
    <%= f.text_field :param_submitter %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end
end%>
</div>

</div>

app/views/videos/_videos.html.erb
<br/><br/>
<div id="playlist" 
     style="font-size: 15px;
     float:right;
     text-align: left;
     width:400px;
     height:400px;
     overflow:scroll;
     overflow-y:scroll;
     overflow-x:hidden;
     padding: 0px 10px;"
     class="wgc-bubble" >
  <ul style="list-style-type: none;">
    <%@i=0; @videos.each do |video|
      @i=@i+1%>

      <li style="padding-bottom: 20px;">
        <div id="wcc_video_<%=video.id%>_begin_tag_<%=video.param_title%>_end_tag_results_thumb_number_<%=@i%>" class="<%=video.param_title%>">
          <a href="<%=video.param_video_url%>">

            <div style="">
              <%=image_tag( video.param_thumb,{:class => "video_thumb"} )%>

              <div style="vertical-align: text-top;float: right;">
                <h3> <%= if video.param_title.length > 10
                    video.param_title[0,10]+"..."
                  else
                    video.param_title[0,10]
                  end
                %>
                </h3>
                <div style="text-align: center">
                  <%= if video.param_desc.length > 10
                    video.param_desc[0,10]+"..."
                  else
                    video.param_desc[0,10]
                  end
                %>
                </div>
              </div>
            </div>

          </a>
        </div>
      </li>

    <% end %>
  </ul>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= form_for(@video) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :param_title %><br />
    <%= f.text_field :param_title %>
  </p>
  <p>
    <%= f.label :param_doc %><br />
    <%= f.date_select :param_doc %>
  </p>
  <p>
    <%= f.label :param_size %><br />
    <%= f.text_field :param_size %>
  </p>
  <p>
    <%= f.label :param_path %><br />
    <%= f.text_field :param_path %>
  </p>
  <p>
    <%= f.label :param_hits %><br />
    <%= f.text_field :param_hits %>
  </p>
  <p>
    <%= f.label :param_mark %><br />
    <%= f.text_field :param_mark %>
  </p>
  <p>
    <%= f.label :param_desc %><br />
    <%= f.text_field :param_desc %>
  </p>
  <p>
    <%= f.label :param_type %><br />
    <%= f.text_field :param_type %>
  </p>
   <p>
    <%= f.label :movieclip %><br />
    <%= f.file_field :movieclip %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/edit_wiki.html.erb
<h1>Editing wiki video</h1>

<% form_for(@video) do |f| %>
  <%= f.error_messages %>

<%@video = Video.find(1)%>
  <p>Date of creation<br/>
  <%= f.date_select   :param_wiki_date %>
</p>
<p>Author<br/>
  <%=f.text_field   :param_wiki_author %>
</p>
<p>Counrty from<br/>
  <%=f.text_field   :param_wiki_country %>
</p>
<p>Clip history<br/>
  <%=f.text_area   :param_wiki_story %>
</p>
<p>Web relative links<br/>
  <%=f.text_field   :param_wiki_links %>
</p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<table style="margin-left: auto;margin-right: auto;text-align: left;padding-bottom: 10px;">
  <tr>
    <td style="text-align: center;" >
      <%= button_to "UPLOAD A NEW CLIP", {:action => "new"  }, {:style => "font-size:30px", :method => :get} %>
    </td>
  </tr>
  <tr>
    <td style="text-align: center;" >
    </td>
  </tr>

</table>

<h1 style="text-align: center">GARBAGE FLOW</h1>
<div id="playlist"
     style="width:967px;height:150px;overflow-y:hidden;overflow-x:scroll;background: none"

     class="wgc-bubble">
  <ul style="width:200%;">
    <%@i=0; @videos.each do |video|
      @i=@i+1 %>
      <li style="float: left;margin-left: 30px;list-style: none">
        <a id="wcc_video_<%=video.id%>_begin_tag_<%=video.param_title%>_end_tag_flow_thumb" href="<%=video.param_video_url%>" >
          <%=image_tag video.param_thumb , {:class => "video_thumb"} %>
        </a>
      </li>
    <% end %>
  </ul>
</div>  

<table style="margin-left: auto;margin-right: auto;text-align: left;padding-bottom: 10px;">
  <tr>
    <td>
      <!-- products/index.html.erb -->
      <%= form_tag videos_path, :method => 'get', :id => "videos_search", :remote => true do %>
        <%= text_field_tag :search, params[:search], {:size => "60", :maxlength => 255, :style => "font-size: 30px" } %>
      </td>
    </tr>

    <tr>
      <td style="text-align: center;">
        <%= submit_tag "SEARCH", { :id => "videos_search_submit" ,:name => nil , :style => "font-size:30px" } %>
      </td>
    </tr>
  </table>
<% end %>


<div id ="RESULTS" style="float:right; text-align: center;font-size: 30px;">
  <h3 style="font-size: 20px">RESULTS</h3>
  <div id="videos"><%= render 'videos' %>
  </div>
</div>

<%=
@initVideo = Video.new();
@initVideo.param_title = "Welcome to WGC !";

render :file => "videos/player.html" , :locals => {:video => @initVideo } %>

<%= render :file => "videos/ad.html" %>


<%= render :partial => 'show_wiki' , :locals => {:myId  => 1} %>
<%#= link_to "Vote Yes", {:controller=>"videos", :action => 'show_wiki',:id=>5, :vote=>true}, :remote=> true, :class=> "yes-button" %>
<%#= link_to 'show_wiki',
'videos/1/show_wiki',
:update => 'wiki_video',
:url => 'http://www.google.fr',
:id => "testAJAX",
:remote => :true%>


<%#*<ul>%>
<%# for video in @videos %>
<%#*<li><%= video.param_title %>
<%#= link_to image_tag(video.param_thumb), video_path(video)%>
<%#= video.param_path %>
<%#= link_to 'view', video_path(video) %>
<%#*</li>%>
<%# end %>
<%#*</ul>%>


<%#=   link_to_remote(image_tag("favicon.jpg"), :update => "emails",
:url => { :action => "_show_wiki" })%>

<%#=link_to_remote image_tag('favicon.jpg'),  {:controller => 'videos', :action => 'show_wiki', :id => 1},:update => 'http://www.google.fr' %>

app/views/videos/index.js.erb
<!-- products/index.js.erb -->
$("#videos").html("<%= escape_javascript(render("videos")) %>");



<%#*alert("hello");%>

<%#*alert(333);%>

app/views/videos/new.html.erb
<div id="NewVideoTitle" style="text-align: center">
  <h1>Import a new video</h1>
</div>
<%# form_for(@video) do |f| %>
<%= form_for(@video, :html => {:multipart => true, :class => 'styledform' } ) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="width: 950px;height: 250px;border: 0px double red;margin: 0 auto; padding: 0 0;">

    <table style="text-align: center">

      <tr>
        <td>  <%= f.label "Video title",{},{:style => "font-size:30px"} %><br /><br />
          <%= f.text_field :param_title,{:style => "font-size:20px"}  %></td>
        <td rowspan="2"> <%= f.label "Video description" ,{},{:style => "font-size:30px"} %><br /><br />
          <%= f.text_area :param_desc,{:rows => 10} %>
        </td>
      </tr>
      <tr>
        <td>
<%#= f.label "Browse video file",{},{:style => "font-size:30px"} %>
          <%#*<br />%>
          <%= f.file_field :movieclip,{:style => "font-size:30px"} %></td>

      </tr>
      <tr>

      </tr>
      <tr>
  <td>  <%= f.label :md5%>
  <br />
  <%= f.text_field :md5 %>
  </td>
        <td colspan="2">  <br/><br/><%= f.submit '         Upload        ',{:style => "font-size:30px"} %> </td>

      </tr>

    </table>

  <% end %>
</div>



<div id="loading" style="display: none">!!!!!!!!!!LOADING!!!!!!!!!!!!</div>

<div id="clearnew" style="padding: 50px 0"></div>
<%#= link_to 'Back', videos_path %>

<%#*<iframe id="secondFrame" name="secondFrame" width="50%" height="500em" frameborder="1" scrolling="auto" src="/videos/uploadprogress/sqd">%>
 <%#*sqdsqd%>
<%#*</iframe>%>

<input type='button' onclick='get_upload_progress($("#video_md5").val())' value='MD5'/>

app/views/videos/show.html.erb
<%= javascript_include_tag "show_wiki"  %>
<%=image_tag @video.param_thumb , { :style => "float: right; opacity: 0.09;" } %>
<%= render :file => "videos/player.html",
  :locals =>
  {:video => @video  } %>
<%= render :file => "videos/ad.html" %>
<%=render :partial => "show_wiki" %>





<%#*<p>%>
<%#*<b>Param title:</b>%>
<%#=h @video.param_title %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param doc:</b>%>
<%#=h @video.param_doc %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param size:</b>%>
<%#=h @video.param_size %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param path:</b>%>
<%#=h @video.param_path %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param hits:</b>%>
<%#=h @video.param_hits %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param mark:</b>%>
<%#=h @video.param_mark %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param desc:</b>%>
<%#=h @video.param_desc %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param type:</b>%>
<%#=h @video.param_type %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param title:</b>%>
<%#=h @video.param_title %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param doc:</b>%>
<%#=h @video.param_doc %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param size:</b>%>
<%#=h @video.param_size %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param path:</b>%>
<%#=h @video.param_path %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param hits:</b>%>
<%#=h @video.param_hits %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param mark:</b>%>
<%#=h @video.param_mark %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param desc:</b>%>
<%#=h @video.param_desc %>
<%#*</p>%>

<%#*<p>%>
<%#*<b>Param type:</b>%>
<%#=h @video.param_type %>
<%#*</p>%>


<%#= render :partial => @video.wikis  %>

<%#= form_for [ @videos, Wiki.new ] do |f| %>

<%#*<div class="field">%>
<%#= f.label :param_desc %><br />
<%#= f.text_field :param_desc %>
<%#*</div>%>
<%#*<div class="actions">%>
<%#= f.submit %>
<%#*</div>%>
<%# end %>

<%#*<p>%>
<%#= link_to "New Wiki", new_wiki_path(:video_id => @video) %> 
<%#= link_to "View All Videos", videos_path %>
<%#*</p>%>

app/views/videos/show_wiki.html.erb
<%=render "show_wiki"%>